
CREATE TABLE EVAL_TIP_GESTION (
    N_ID_TIPO_GESTION NUMBER PRIMARY KEY,
    C_DESCRIPCION VARCHAR2(100) NOT NULL,
    N_PESO NUMBER(10,2),
    N_ESTADO NUMBER(1) DEFAULT 1,
    C_USU_REGISTRO VARCHAR2(50),
    D_FEC_REGISTRO DATE
);

INSERT INTO EVAL_TIP_GESTION (N_ID_TIPO_GESTION, C_DESCRIPCION, N_PESO, N_ESTADO, C_USU_REGISTRO, D_FEC_REGISTRO)
VALUES (3, 'Gestión Visa', 60, 1, 'GNOAIN', TO_DATE('19/11/2018 21:19:00', 'DD/MM/YYYY HH24:MI:SS'));

INSERT INTO EVAL_TIP_GESTION (N_ID_TIPO_GESTION, C_DESCRIPCION, N_PESO, N_ESTADO, C_USU_REGISTRO, D_FEC_REGISTRO)
VALUES (4, 'Gestión MC', 50, 1, 'GNOAIN', TO_DATE('19/11/2018 21:19:00', 'DD/MM/YYYY HH24:MI:SS'));

INSERT INTO EVAL_TIP_GESTION (N_ID_TIPO_GESTION, C_DESCRIPCION, N_PESO, N_ESTADO, C_USU_REGISTRO, D_FEC_REGISTRO)
VALUES (5, 'Contracargo Visa', 0, 1, 'GNOAIN', TO_DATE('19/11/2018 21:19:00', 'DD/MM/YYYY HH24:MI:SS'));

INSERT INTO EVAL_TIP_GESTION (N_ID_TIPO_GESTION, C_DESCRIPCION, N_PESO, N_ESTADO, C_USU_REGISTRO, D_FEC_REGISTRO)
VALUES (6, 'Contracargo MC', 0, 1, 'GNOAIN', TO_DATE('19/11/2018 21:19:00', 'DD/MM/YYYY HH24:MI:SS'));

COMMIT;

SELECT N_ID_TIPO_GESTION, C_DESCRIPCION, N_PESO, N_ESTADO, C_USU_REGISTRO, TO_CHAR(D_FEC_REGISTRO, 'DD/MM/YYYY HH24:MI:SS') AS D_FEC_REGISTRO
FROM EVAL_TIP_GESTION;

